### ISSUE TITLE
How to set up the prometheusremotewrite expoter to send metrics to AMP in other region?

### ISSUE THREAD

**Issue by John1Q84** [aws-observability/aws-otel-community#102]
First of all, I have set vpc peering, routing, internal dns setting on route53 as referring, [this blog post](https://aws.amazon.com/ko/blogs/opensource/set-up-cross-region-metrics-collection-for-amazon-managed-service-for-prometheus-workspaces/) 
However, when I deployed otel-collector with the PrometheusRemoteWrite exporter, it went to failed with below error message. 
``` cannot build pipelines: failed to create "prometheusremotewrite" exporter, in pipeline "metrics": invalid endpoint``` 

Here is my otel-collector yaml file snippet 
 Along with below yaml, my EKS cluster is in ap-northeast-2 region, and AMP set on the ap-norteast-1 region. 

```
 mode: deployment
  serviceAccount: amp-iamproxy-ingest-role

  config: |
    extensions:
      sigv4auth:
        region: "ap-northeast-1"
        service: "aps"

    receivers:
      prometheus:
        config:
          global:
            scrape_interval: 15s
            scrape_timeout: 10s
...
...
            - __meta_kubernetes_pod_phase

    processors:
      batch/metrics:
        timeout: 60s

    exporters:
      prometheusremotewrite:
        endpoint: "https://aps-workspaces.ap-northeast-1.amazonaws.com/workspaces/ws-40bfe141-xxxx-xxxx-xxxx-950de13a5ab5/api/v1/remote_write"
        auth:
          authenticator: sigv4auth
        # external_labels:
          # label_name1: some_value1
          # label_name2: some_value2

    service:
      extensions: [sigv4auth]
      pipelines:
        #
        # Metrics pipeline for collecting Prometheus metrics and sending them to Amazon Managed Prometheus
        #
        metrics:
          receivers: [prometheus]
          processors: [batch/metrics]
          exporters: [prometheusremotewrite]
```

**Comment by John1Q84** [comment]
I found the way, 
To send out the prometheus metrics to other region by using `prometheus remote write` exporter, `awsproxy` extension is required.


```
extensions: 
  sigv4auth: 
    region: "us-east-1"
    service: "aps"
  awsproxy: 
    region: "us-east-1"
..
...
....
 service:
      extensions: [sigv4auth, awsproxy]
      pipelines:
        #
        # Metrics pipeline for collecting Prometheus metrics and sending them to Amazon Managed Prometheus
        #
        metrics:
          receivers: [prometheus]
          processors: [batch/metrics]
          exporters: [prometheusremotewrite]
```
