### ISSUE TITLE
Help confirming otlp reciever configuration

### ISSUE THREAD

**Issue by sbowers-gbx** [aws-observability/aws-otel-community#178]
Hello,

I'm exploring the [otel golang trace sdk](go.opentelemetry.io/otel/sdk/trace) and have had trouble with both the otlptracegrpc and otlptracehttp exporters establishing successful communication with my adot-otel sidecar's [otlp reciver configurations](https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/otlpreceiver ).

I've implemented a proof of concept [otelgin](https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin) endpoint in my testing app.
I've got an adot-otel-collector running with this summarized config:

# ADOT Collector Config
```yml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318
        
processors:
  batch:
    timeout: 10s  
        
exporters:
  logging:
    loglevel: info
    sampling_initial: 5
    sampling_thereafter: 200
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/datadogexporter/example/config.yaml
  datadog:
    api:
      key: "nope"
    metrics:
      resource_attributes_as_tags: true
    traces:
      ignore_resources: ["(GET|POST|HEAD) /servicehealth"]

service:
  telemetry:
    logs:
      level: "warn"
  extensions: [health_check,zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, datadog]
```

## ADOT docker-compose
```yml
  otel:
    image: public.ecr.aws/aws-observability/aws-otel-collector:v0.24.1
    ports:
      - "8125:8125"
      - "4317:4317"
      - "4318:4318"
    command: "--config=/etc/otel/config.yaml"
    volumes:
      - ./otel-config-local.yml:/etc/otel/config.yaml
    networks:
      - development
```

# Golang Code
For the otlptracehttp connection I've pretty much copy/pasted from examples, and the resulting logs suggest that this copied golang code is working as expected:
```go
func InitTracer(ctx context.Context) *trace.TracerProvider {
	// ATTEMPT at HTTP (uses default endpoint Post "http://localhost:4318/v1/traces")
	client := otlptracehttp.NewClient(
		otlptracehttp.WithInsecure(),
	)
	traceExporter, err := otlptrace.New(ctx, client)
	if err != nil {
		logging.Fatal(ctx, "idk some http client issue %s", err)
	}

	// Register the trace exporter with a TracerProvider, using a batch
	// span processor to aggregate spans before export.
	bsp := trace.NewBatchSpanProcessor(traceExporter)

	// create a resource with our preferred attributes
	//    https://pkg.go.dev/go.opentelemetry.io/otel/sdk@v1.11.2/resource
	r, err := resource.New(ctx, resource.WithAttributes(semconv.ServiceNameKey.String("sbowers-api")))
	if err != nil {
		log.Fatal(err)
		return nil
	}

	// merge that custom resource with the default resource (letting our custom values override in any collision scenario)
	resource, err := resource.Merge(resource.Default(), r)
	if err != nil {
		log.Fatal(err)
		return nil
	}

	// create the TracerProvider
	tp := trace.NewTracerProvider(
		trace.WithSampler(trace.AlwaysSample()),
		// trace.WithBatcher(exporter), // comment out if using OTLP exporter, only for stdout exporter.
		trace.WithResource(resource),
		trace.WithSpanProcessor(bsp), // commount out if using STDOUT expoter, only for otlp exporter.
	)

	// set that tp as our global Otel TracerProvider
	otel.SetTracerProvider(tp)

	// take example propagation settings for now
	otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(propagation.TraceContext{}, propagation.Baggage{}))

	// return our TracerProvider object fully configured
	return tp
}
```

## Golang Log lines
From my golang service logs:
```
2022/12/16 16:46:03 Post "http://localhost:4318/v1/traces": dial tcp 127.0.0.1:4318: connect: connection refused
```

From a local terminal just testing that endpoint's existence:
```bash
curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST http://localhost:4318/v1/traces
curl: (52) Empty reply from server
```

Any suggestions for fixing my ADOT OTLPRECEIVER configuration to accept insecure connections via http and/or grpc would be appreciated.
If I can provide better or further information I'll be glad to.

Thanks in advance,
Scott Bowers

**Comment by bryan-aguilar** [comment]
Is [TLS Insecure](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configtls/README.md) what you are looking for?

**Comment by sbowers-gbx** [comment]
Maybe, but I think I'm having trouble getting the syntax right.

Is this a valid receivers section?

```yml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318
        tls:
          insecure_skip_verify: true

**Comment by bryan-aguilar** [comment]
Can you try using `0.0.0.0` instead of local host?

**Comment by sbowers-gbx** [comment]
Definitely, that was where I started before seeing the warning here: https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks 

So ignoring that for now since I'm trying to be insecure anyways:
```yml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        tls:
          insecure: false
          insecure_skip_verify: true
```
Note: the below defaults to localhost.
> 2022/12/16 18:00:22 Post "https://localhost:4318/v1/traces": dial tcp 127.0.0.1:4318: connect: connection refused

I went and specifically rewrote the default to be sure:
```go
	client := otlptracehttp.NewClient(
		otlptracehttp.WithEndpoint("0.0.0.0:4318"),
	// otlptracehttp.WithInsecure(),
	)
```

> 2022/12/16 18:04:18 Post "https://0.0.0.0:4318/v1/traces": dial tcp 0.0.0.0:4318: connect: connection refused
