### ISSUE TITLE
Prometheus Remote Write Exporter for AMP Credential error

### ISSUE THREAD

**Issue by hiranthaPeiris** [aws-observability/aws-otel-community#28]
Hi, 
I am trying to configure AMP exporter but get NoCredentialProviders on logs of the collector as following.
`       WARN        batchprocessor/batch_processor.go:209        Sender failed        {"kind": "processor", "name": "batch/metrics", "error": "Permanent error: Post \"https://aps-workspaces.us-east-1.<workspace>/api/v1/remote_write\": NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"}`

I have set aws access key according to default AWS credentials chain and also AWS go SDK as the documentation. what I could be missing here?

Thanks

**Comment by alolita** [comment]
Hi @hiranthaPeiris Can you share more about your setup and version of the PRW Exporter? Thx.

**Comment by hiranthaPeiris** [comment]
hi @alolita ,
am running the latest otel and here is the config for the collector. 
```
extensions:
  health_check:

receivers:
  prometheus:
    config:
      global:
        scrape_interval: 1m
        scrape_timeout: 10s

      scrape_configs:
        - job_name: "strs-opentel"

          scrape_interval: 5s

          static_configs:
            - targets: ["localhost:9100"]
              labels:
                group: "UAT-opentel"

processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 50
  batch/metrics:
    timeout: 60s

exporters:
  awsprometheusremotewrite:
    endpoint: "https://aps-workspaces.us-east-1.amazonaws.com/workspaces/<workspaceID>/api/v1/remote_write"
    aws_auth:
      service: "aps"
      region: "us-east-1"

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch/metrics]
      exporters: [awsprometheusremotewrite]

  extensions: [health_check]
```

and also credentials works fine with aws cli. tried with both shared folder and env var but the result came same.
