### ISSUE TITLE
YAML configuration docs?

### ISSUE THREAD

**Issue by aclarknexient** [aws-observability/aws-otel-community#54]
Hello,

I'm deploying a aws-otel-collector instance as an ECS service using fargate, with a plain http AWS load balancer in front. Currently my ECS task is failing with a "read from UDP socket: read udp [::]:2000: use of closed network connection" message, and I was wondering exactly what I can disable to debug things. Is there a document that details what can go into the configuration yaml file?

Is it possible to just remove the awsxray related stuff below if I know we won't use it?

Many thanks!

```yaml
extensions:
  health_check:
receivers:
  awsxray:
    endpoint: 0.0.0.0:2000
    transport: udp
  otlp:
    protocols:
      grpc:
        endpoint:
      http:
        endpoint:
processors:
  batch/traces:
    timeout: 5s
    send_batch_size: 256
  resourcedetection:
    detectors: [env, ec2, ecs]
    timeout: 5s
    override: true
exporters:
  otlphttp:
    endpoint: REDACTED
service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [awsxray,otlp]
      processors: [resourcedetection,batch/traces]
      exporters: [otlphttp]
```
