### ISSUE TITLE
aws otel collector supported jaeger receiver remote_sampling configuration doesn't work

### ISSUE THREAD

**Issue by masru89xyz** [aws-observability/aws-otel-community#59]
Hi folk. I am using jaeger as the trace data receiver and without **remote_sampling** configuration, it's working fine but if I configure remote_sampling then I get an error. 

**Here is the error,**

`aws-ot-collector_1  | Error: failed to get config: invalid configuration: receiver "jaeger" has invalid configuration: unable to extract port for the Remote Sampling endpoint: endpoint is not formatted correctly: missing port in address
aws-ot-collector_1  | 2022/04/18 09:25:59 application run finished with error: failed to get config: invalid configuration: receiver "jaeger" has invalid configuration: unable to extract port for the Remote Sampling endpoint: endpoint is not formatted correctly: missing port in address`

**And the configuration is,**

```
extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777

receivers:
  jaeger:
    protocols:
      grpc:
    remote_sampling:
      endpoint: "jaeger:14268"
      tls:
        insecure: true
      strategy_file: "/etc/strategies.json"
      strategy_file_reload_interval: 10s

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  awsxray:
    region: 'us-west-2'

service:
  pipelines:
    traces:
      receivers: [jaeger]
      exporters: [awsxray]

  extensions: [pprof]
  telemetry:
    logs:
      level: debug
```

Please help me if anyone knows where I am doing wrong.  I would like to provide more info if needed. Thanks
