### ISSUE TITLE
attributes processor in ADOT lambda layer

### ISSUE THREAD

**Issue by fschollmeyer** [aws-observability/aws-otel-community#804]
Hi everyone,

I'm trying to add a attributes processor to the config of an ADOT collector, added as lambda layer to a nodejs lambda. I'm using the latest layer version: arn:aws:lambda:eu-central-1:901920570463:layer:aws-otel-nodejs-amd64-ver-1-17-1:1

When I define an attributes processor, I get the following error:  "error": "failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:\n\n* error decoding 'processors': unknown type: \"attributes\" for id: \"attributes/test\" (valid values: []); Post `\"http://127.0.0.1:9001/2020-01-01/extension/init/error\": net/http: invalid header field value for \"Lambda-Extension-Function-Error-Type\"",`

I define the processor like this at the root of my config:
```processors:
  attributes/test:
    actions:
      - key: account
        action: upsert
        value: some value
```

Browsing through the different kind of documentation it is not clear to me, whether this feature is not supported or wheter I'm doing a mistake.

The upstream otel-lambda seems to contain it: https://github.com/open-telemetry/opentelemetry-lambda/blob/main/collector/lambdacomponents/default.go

I cannot really figure out, where the configuration or the ADOT lambda layers is done.

Thanks for your support,
Felix

**Comment by mhausenblas** [comment]
Thanks for raising this @fschollmeyer. See [aws-observability/aws-otel-lambda](https://github.com/aws-observability/aws-otel-lambda#adot-lambda-layer-available-components) for the components included in the Lambda ADOT collector variant. As you can see from there, we don't include this component.

**Comment by fschollmeyer** [comment]
Is that list really exhaustive? It does e.g. not list the jaeger exporter,  which I am successfully using.

**Comment by bryan-aguilar** [comment]
Can you share your entire collector configuration?

**Comment by fschollmeyer** [comment]
Hi @bryan-aguilar ,
sure. 

This configuration works:
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318
exporters:
  otlp/jaeger:
    endpoint: jaeger-collector.:4317
    tls:
      insecure: true
  logging/traces:
    verbosity: detailed
processors: {}
service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors: []
      exporters:
        - otlp/jaeger
        - logging/traces
   ```

This one doesn't:
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318
exporters:
  otlp/jaeger:
    endpoint: jaeger-collector.:4317
    tls:
      insecure: true
  logging/traces:
    verbosity: detailed
processors:
  attributes/test:
    actions:
      - key: account
        action: upsert
        value: some value
service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - attributes/test
      exporters:
        - otlp/jaeger
        - logging/traces
   ```
Note that I set them as JSON string via env-confmap provider.

**Comment by bryan-aguilar** [comment]
I see, but to be clear 
```
  otlp/jaeger:
    endpoint: jaeger-collector.:4317
    tls:
      insecure: true
```
is not a jaeager exporter. It is an `otlp` exporter which uses the `/jaeger` as a unique identifier.
