### ISSUE TITLE
Getting Metrics to flow in AWS Distro for OpenTelemetry Lambda Support For Python

### ISSUE THREAD

**Issue by rberger** [aws-observability/aws-otel-community#85]
Using the  current release `arn:aws:lambda:\<region>:901920570463:layer:aws-otel-python-amd64-ver-1-11-1:1` it looks like Opentelemetry metrics are available in the SDK used in a lambda with the above lambda layer if you import `_metrics`. At least it doesn't give an error. 

But I can not get metrics to actually flow to an exporter. I have tried something based on the Python metrics  [example in the Opentelemetry docs](https://opentelemetry.io/docs/instrumentation/python/getting-started/#metrics) (shown below). The only difference was I could not get the 
```
processors:
  batch:
```
in the collector config.yml to  work in the v1.11.1 lambda. It would always crash the extension. I presume that things are related to that.

I also tried to use the metrics example from the v1.11.1 [opentelemetry-python](https://github.com/open-telemetry/opentelemetry-python/blob/release/1.11.1-0.30b1/docs/examples/metrics/example.py) but could not import from `opentelemetry.exporter.otlp.proto.grpc._metric_exporter` as it seemed to not be available in the aws python lambda layer. Also it had the processors batch line in the collector config.yaml that would cause the lambda to crash.

Here is the lambda code and the collector config.yml I was trying:

```
import os
import json
from opentelemetry import trace
from typing import Iterable
from opentelemetry import _metrics
from random import randint
import time

# Acquire a tracer
tracer = trace.get_tracer(__name__)

# Acquire a meter and create a counter
meter = _metrics.get_meter(__name__)

my_counter = meter.create_counter(
    "my_counter",
    description="My Counter counting",
)
       
# The lambda H
def handler(event, context):
    with tracer.start_as_current_span("top") as topspan:
        res = randint(1, 6)

        # Counter
        my_counter.add(1, {"res.value": res})

        json_region = os.environ['AWS_REGION']
        topspan.set_attribute("region", json_region)
        topspan.set_attribute("res.value", res)
        time.sleep(10)
        return {
            "statusCode": 200,
            "headers": {
                "Content-Type": "application/json"
            },
            "body": json.dumps({
                "Region ": json_region,
                "res ": res
            })
        }
```

I've tried many variations of this, none end up exporting metrics to honeycomb (or the logger as far as I can tell) Traces do flow to Honeycomb.

```
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug
  awsxray:
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers: {
      "x-honeycomb-team": "Qf0n7UBOs2sG3DL7SA8CDD",
      "x-honeycomb-dataset": "rob"
    }
  otlp/metrics:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "Qf0n7UBOs2sG3DL7SA8CDD"
      "x-honeycomb-dataset": "rob"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [logging, awsxray, otlp]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [logging, otlp/metrics]
```

Ether I'm doing something wrong (highly probable) or the v1.11.1 AWS Lambda layer for Python is not quite supporting metrics. Hard for me to tell right now and can't find any explicit examples for metrics and the AWS Python Lambda Layer. Any help would be appreciated!
