### ISSUE TITLE
Prevent AMP from collecting EKS cluster metrics (30$ per day)

### ISSUE THREAD

**Issue by hdsuperman** [aws-observability/aws-otel-community#857]
After turning on amp, a large amount of cluster metrics information was collected, and the cost was close to 30$ per day.
As developers we only care about the metrics of a specific container. Ability to determine what information is collected by controlling the service's annotation.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: abc
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
    prometheus.io/port: '18080'
spec:
  selector:
    app: abc
  ports:
    - name: restful
      protocol: TCP
      port: 18080
      targetPort: 18080
    - name: grpc
      protocol: TCP
      port: 19090
      targetPort: 19090
```

Is there any way to achieve the above requirements by controlling the json configuration of the adot add-on?
