### ISSUE TITLE
https://github.com/aws-observability/aws-otel-community/blob/master/sample-configs/operator/collector-config-xray.yaml

### ISSUE THREAD

**Issue by lifeofmoo** [aws-observability/aws-otel-community#888]
Hello,

I've been playing around with the Adot implementation for the past several months and everything was working fine. I've started to revisit this as i'm looking to do do some eventbridge and PagerDuty in 2024.

I've had it deployed across all my eks clusters for while but now seeing this error:

eks: v1.25 
Adot Operator = v0.82.0-eksbuild.1

The Operator installs fine into the opentelemetry-operator-system NS:

```NAME                                          READY   STATUS    RESTARTS   AGE
pod/opentelemetry-operator-75b5b48d57-4xnlr   2/2     Running   0          25m

NAME                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
service/opentelemetry-operator           ClusterIP   10.100.55.136   <none>        8443/TCP,8080/TCP   25m
service/opentelemetry-operator-webhook   ClusterIP   10.100.145.90   <none>        443/TCP             25m

NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/opentelemetry-operator   1/1     1            1           25m

NAME                                                DESIRED   CURRENT   READY   AGE
replicaset.apps/opentelemetry-operator-75b5b48d57   1         1         1       25m
```
I've then installed the following collector into a NS called: opentelemetry, which hasn't changed in the several months and was working fine.

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: collector-xray
spec:
  mode: deployment
  resources:
    requests:
      cpu: "1"
    limits:
      cpu: "1"
  serviceAccount: adot-collector
  env:
    - name: CLUSTER_NAME
      value: eksdev
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch/traces:
        timeout: 1s
        send_batch_size: 50
      resourcedetection/eks:
        detectors: [env, eks]
        timeout: 2s
        override: false

    exporters:
      awsxray:
        region: eu-west-1
        index_all_attributes: true

      logging:
        loglevel: debug
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [resourcedetection/eks, batch/traces]
          exporters: [awsxray,logging]

      telemetry:
        logs:
          level: debug

```

However I'm now seeing this error in the operator logs:

```
{"level":"error","ts":"2023-12-18T12:21:21Z","logger":"controllers.OpenTelemetryCollector","msg":"Cannot create liveness probe.","opentelemetrycollector":{"name":"collector-xray","namespace":"opentelemetry"},"error":"service property in the configuration doesn't contain extensions","stacktrace":"github.com/open-telemetry/opentelemetry-operator/internal/manifests/collector.Container\n\t/workspace/internal/manifests/collector/container.go:127\ngithub.com/open-telemetry/opentelemetry-operator/internal/manifests/collector.Deployment\n\t/workspace/internal/manifests/collector/deployment.go:56\ngithub.com/open-telemetry/opentelemetry-operator/pkg/collector/reconcile.Deployments\n\t/workspace/pkg/collector/reconcile/deployment.go:40\ngithub.com/open-telemetry/opentelemetry-operator/controllers.(*OpenTelemetryCollectorReconciler).RunTasks\n\t/workspace/controllers/opentelemetrycollector_controller.go:237\ngithub.com/open-telemetry/opentelemetry-operator/controllers.(*OpenTelemetryCollectorReconciler).Reconcile\n\t/workspace/controllers/opentelemetrycollector_controller.go:225\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:314\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:226"}
```

Note: I was also half way through migrating to 0.88 but gave up on this due to incomplete info on the migration guide and not introducing extra variables (i.e creating the new IAM role and setting advanced add on config etc).

Any advice would be appreciated.
