### ISSUE TITLE
ADOT Collector message for writing to Prometheus remotely.

### ISSUE THREAD

**Issue by chainhead** [aws-observability/aws-otel-community#96]
After launching ADOT Collector with `sudo /opt/aws/aws-otel-collector/bin/aws-otel-collector-ctl -c $HOME/adot-config.yaml -a start`, the log messages seen are as follows.

```bash
tail -f /opt/aws/aws-otel-collector/logs/aws-otel-collector.log
{"level":"info","timestamp":"2022-09-07T03:49:23.999Z","caller":"pipelines/pipelines.go:78","message":"Exporter is starting...","kind":"exporter","data_type":"metrics","name":"prometheusremotewrite"}
{"level":"info","timestamp":"2022-09-07T03:49:23.999Z","caller":"pipelines/pipelines.go:82","message":"Exporter started.","kind":"exporter","data_type":"metrics","name":"prometheusremotewrite"}
{"level":"info","timestamp":"2022-09-07T03:49:23.999Z","caller":"pipelines/pipelines.go:86","message":"Starting processors..."}
{"level":"info","timestamp":"2022-09-07T03:49:23.999Z","caller":"pipelines/pipelines.go:98","message":"Starting receivers..."}
{"level":"info","timestamp":"2022-09-07T03:49:23.999Z","caller":"pipelines/pipelines.go:102","message":"Receiver is starting...","kind":"receiver","name":"prometheus","pipeline":"metrics"}
{"level":"debug","timestamp":"2022-09-07T03:49:24.000Z","caller":"discovery/manager.go:289","message":"Starting provider","kind":"receiver","name":"prometheus","pipeline":"metrics","provider":"static/0","subs":"map[onpremises_exporter:{}]"}
{"level":"debug","timestamp":"2022-09-07T03:49:24.001Z","caller":"discovery/manager.go:323","message":"Discoverer channel closed","kind":"receiver","name":"prometheus","pipeline":"metrics","provider":"static/0"}
{"level":"info","timestamp":"2022-09-07T03:49:24.002Z","caller":"pipelines/pipelines.go:106","message":"Receiver started.","kind":"receiver","name":"prometheus","pipeline":"metrics"}
{"level":"info","timestamp":"2022-09-07T03:49:24.003Z","caller":"service/collector.go:215","message":"Starting aws-otel-collector...","Version":"v0.21.0","NumCPU":1}
{"level":"info","timestamp":"2022-09-07T03:49:24.003Z","caller":"service/collector.go:128","message":"Everything is ready. Begin running and processing data."}
```

Can you please elaborate what does `Everything is ready.` mean? Is ADOT Collector able to read from receiver _and_ write to exporter successfully? In my case, I am writing to AMP; however, the `awscurl` does not report any metrics. I am not sure where to start debugging. This is my configuration file.

```yaml
receivers:
  prometheus:
    config:
      global:
        scrape_interval: 15s
        external_labels:
          monitor: 'onpremises_exporter'

      scrape_configs:
        - job_name: 'onpremises_exporter'
          static_configs:
            - targets: ['localhost:9103']

extensions:
  sigv4auth:
    service: "aps"
    region: "ap-southeast-1"

exporters:
  prometheusremotewrite:
    endpoint: "https://aps-workspaces.ap-southeast-1.amazonaws.com/workspaces/workspaceId/api/v1/remote_write"
    auth:
      authenticator: sigv4auth

service:
  extensions: [sigv4auth]
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheusremotewrite]
```

**Comment by mhausenblas** [comment]
> Can you please elaborate what does Everything is ready. mean?

It means that you have no mistakes in your collector config and the pipeline you defined is up and running (in your case the one you named `metrics`.

>  Is ADOT Collector able to read from receiver and write to exporter successfully? 

For that to answer we would need to see more of the collector logs, you only shared the start-up sequence.

>  In my case, I am writing to AMP; however, the awscurl does not report any metrics. I am not sure where to start debugging

First check if the receiver works as expected (do metrics arrive in the collector?) and the exporter as well. You can do that be enabling DEBUG level logs:

```
 exporters:
      logging:
        loglevel: debug
...
    metrics:
      receivers: [prometheus]
      exporters: [logging, prometheusremotewrite]
```

With above you should see the DEBUG level collector logs on `stdout`.

In my experience troubleshooting OpenTelemetry collectors it's often the case that IAM settings are lacking or misconfigured. In your case, for example, did you check if the machine you're running the ADOT collector on has an IAM role attached?
